BookStore/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Controllers
{
    public class LogoutController : Controller
    {
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login", "Login");
        }
    }
}

BookStore/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessObject.Models;
using DataAccess.Repository;
using Microsoft.EntityFrameworkCore;

namespace BookStore.Controllers
{
    public class ProductController : Controller
    {
        private readonly MiniProjectContext clrContext;
        public ProductController(MiniProjectContext context)
        {
            clrContext = context;
        }
        public IBookRepository bookRepo = new BookRepository();
        // GET: ProductController
        public async Task<IActionResult>  Index()
        {
            var session = HttpContext.Session;
            if (session.GetString("USER") != null)
            {
                if (session.GetString("ROLEID") == "AD")
                {
                    return View(await clrContext.TblBooks.ToListAsync());
                }
                else
                {
                    return RedirectToAction("Login", "Login");
                }
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
        }

        // GET: ProductController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            if (HttpContext.Session.GetString("ROLEID") == "AD")
            {
                return View();
            }
            return RedirectToAction("Login", "Login");
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TblBook book)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bookRepo.InsertBook(book);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(string id)
        {
            if (HttpContext.Session.GetString("ROLEID") == "US")
            {
                return RedirectToAction("Login", "Login");
            }
            var book = bookRepo.GetBookByID(id);
            if(book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TblBook book)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bookRepo.UpdateBook(book);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(book);
            }
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(string id)
        {
            var book = bookRepo.GetBookByID(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BookStore/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessObject.Models;
using Microsoft.EntityFrameworkCore;
using DataAccess.Repository;

namespace BookStore.Controllers
{
    public class UserController : Controller
    {
        private readonly MiniProjectContext clrContext;
        [TempData]
        public string Message { get; set; }
        public UserController(MiniProjectContext context)
        {
            clrContext = context;
        }
        public IUserRepository userRepo = new UserRepository();
        // GET: UserController
        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("USER") != null)
            {
                if(HttpContext.Session.GetString("ROLEID") == "AD")
                {
                    return View(await clrContext.TblUsers.ToListAsync());
                }
                else
                {
                    return RedirectToAction("Shopping", "Shopping");
                }
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
            
        }

        // GET: UserController/Details/5
        public ActionResult Details(string id)
        {
            id = HttpContext.Session.GetString("USER");
            var user = userRepo.GetUserByID(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // GET: UserController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TblUser user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    userRepo.InsertUser(user);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Edit/5
        public ActionResult Edit(string id)
        {
            if (HttpContext.Session.GetString("ROLEID") != "AD")
            {
                return RedirectToAction("Login", "Login");
            }
            var user = userRepo.GetUserByID(id);
            if(user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( TblUser user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    userRepo.UpdateUser(user);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(user);
            }
        }

        // GET: UserController/Delete/5
        public ActionResult Delete(string id)
        {
            var user = userRepo.GetUserByID(id);
            if(user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: UserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

BookStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Mvc
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand">BookStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetString("ROLEID") == "AD")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else if (Context.Session.GetString("ROLEID") == "US")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Details">View Detail</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="ViewCart">Cart</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Logout" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                    <div class="mr-auto">
                        <label class="text-dark">@Context.Session.GetString("USER")</label>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>